-- MySQL Script generated by MySQL Workbench
-- Qua 22 Out 2014 04:30:06 BRST
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema locafan
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `locafan` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `locafan` ;

-- -----------------------------------------------------
-- Table `locafan`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locafan`.`cliente` (
  `id` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `rg` VARCHAR(50) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `endereco` VARCHAR(100) NOT NULL,
  `tel_fixo` VARCHAR(11) NULL,
  `tel_cel` VARCHAR(11) NOT NULL,
  `tel_trab` VARCHAR(11) NULL,
  `email` VARCHAR(100) NULL,
  `cidade` VARCHAR(100) NOT NULL,
  `uf` VARCHAR(2) NOT NULL,
  `cep` VARCHAR(8) NOT NULL,
  `multa` FLOAT NOT NULL DEFAULT 0.0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_cliente_UNIQUE` (`id` ASC),
  UNIQUE INDEX `rg_cliente_UNIQUE` (`nome` ASC),
  UNIQUE INDEX `cpf_cliente_UNIQUE` (`rg` ASC),
  UNIQUE INDEX `nome_cliente_UNIQUE` (`cpf` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `locafan`.`locacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locafan`.`locacao` (
  `id` INT NOT NULL,
  `dt_locacao` DATE NOT NULL,
  `dt_devolucao` DATE NOT NULL,
  `pg_realiazado` FLOAT NOT NULL,
  `cliente_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idlocacao_UNIQUE` (`id` ASC),
  INDEX `fk_locacao_cliente_idx` (`cliente_id` ASC),
  CONSTRAINT `fk_locacao_cliente`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `locafan`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `locafan`.`fantasia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locafan`.`fantasia` (
  `id` INT NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  `tipo` VARCHAR(50) NOT NULL,
  `tema` VARCHAR(50) NOT NULL,
  `disponibilidade` TINYINT(1) NOT NULL,
  `valor` FLOAT NOT NULL,
  `valor_locacao` FLOAT NOT NULL,
  `locacao_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_fantasia_UNIQUE` (`id` ASC),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC),
  INDEX `fk_fantasia_locacao1_idx` (`locacao_id` ASC),
  CONSTRAINT `fk_fantasia_locacao1`
    FOREIGN KEY (`locacao_id`)
    REFERENCES `locafan`.`locacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
